In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [2]:
final=pd.DataFrame()
for a in range(1,199):
    url='https://internshala.com/internships/page-{}/'.format(a)
    webpage=requests.get(url).text
    soup=BeautifulSoup(webpage,'lxml')
    company=soup.find_all('div',class_="internship_meta duration_meta")
    name=[]
    stipend=[]
    location=[]
    hiring=[]
    all_skills = [] 
    for i in company:
        name.append(i.find("p").text.strip())
        stipend.append(i.find("span",class_="stipend").text.removesuffix("/month"))
        location.append(i.find("a").text)
        badge = i.find("div", class_="actively-hiring-badge")
        hiring.append(badge.text if badge else "Not actively hiring")

        company_skills = []
        skill_divs = i.find_all("div", class_="job_skill")
        for div in skill_divs:
            company_skills.append(div.text.strip())
        all_skills.append(company_skills)
    df = pd.DataFrame({
    'Name':name,'location':location,'stipend':stipend,"company_id": range(len(all_skills)),
    "skills": all_skills,"hiring":hiring
    })
    final = pd.concat([final, df], ignore_index=True)

In [3]:
final

,Name,location,stipend,company_id,skills,hiring
0,Shades Of India,Retail Merchandise,"₹ 3,000",0,[MS-Excel],Not actively hiring
1,Whistlefetch Technologies Private Limited,Field Marketing Operations And Growth,"₹ 15,000 - 20,000",1,"[Social Media Marketing, Field Work, English P...",Actively hiring
2,Klearprop,Real Estate Field Research Executive,"₹ 8,000 - 12,000",2,"[Attention to Detail, Time Management, Report ...",Actively hiring
3,Export Genius,Business Development (Sales),"₹ 10,000 - 12,000",3,"[Digital Marketing, Email Marketing, Sales Man...",Actively hiring
4,WAH FILMS,Video Editing/Making,"₹ 15,000",4,"[Adobe Photoshop, Video Editing, Adobe Premier...",Actively hiring
...,...,...,...,...,...,...
7902,Connect Karo,Community Growth & Marketing Intern,"₹ 5,000 - 10,000",12,"[Social Media Marketing, Leadership, Event Man...",Not actively hiring
7903,Mckinsey,Business Analyst Intern,Competitive stipend,13,"[MS-PowerPoint, MS-Excel, Effective Communicat...",Not actively hiring
7904,Mckinsey,Associate Intern,Competitive stipend,14,"[MS-PowerPoint, MS-Excel, Effective Communicat...",Not actively hiring
7905,Qualcomm,Interim Engineering Intern,Competitive stipend,15,"[Linux, Unix, C Programming, C++ Programming, ...",Not actively hiring
7906,Qualcomm,Interim Engineering Intern,Competitive stipend,16,"[MATLAB, Linux, Unix, Algorithms, C Programmin...",Not actively hiring

In [4]:
file_path ="C:\Year 2\Sem 4\SGP\Smart-Internship-Matchmaker\Data\WebScraping_Data.csv"

In [5]:
final.to_csv(file_path, index=False, encoding="utf-8")

In [6]:
df=pd.read_csv("C:\Year 2\Sem 4\SGP\Smart-Internship-Matchmaker\Data\WebScraping_Data.csv")

In [7]:
df

,Name,location,stipend,company_id,skills,hiring
0,Shades Of India,Retail Merchandise,"₹ 3,000",0,['MS-Excel'],Not actively hiring
1,Whistlefetch Technologies Private Limited,Field Marketing Operations And Growth,"₹ 15,000 - 20,000",1,"['Social Media Marketing', 'Field Work', 'Engl...",Actively hiring
2,Klearprop,Real Estate Field Research Executive,"₹ 8,000 - 12,000",2,"['Attention to Detail', 'Time Management', 'Re...",Actively hiring
3,Export Genius,Business Development (Sales),"₹ 10,000 - 12,000",3,"['Digital Marketing', 'Email Marketing', 'Sale...",Actively hiring
4,WAH FILMS,Video Editing/Making,"₹ 15,000",4,"['Adobe Photoshop', 'Video Editing', 'Adobe Pr...",Actively hiring
...,...,...,...,...,...,...
7902,Connect Karo,Community Growth & Marketing Intern,"₹ 5,000 - 10,000",12,"['Social Media Marketing', 'Leadership', 'Even...",Not actively hiring
7903,Mckinsey,Business Analyst Intern,Competitive stipend,13,"['MS-PowerPoint', 'MS-Excel', 'Effective Commu...",Not actively hiring
7904,Mckinsey,Associate Intern,Competitive stipend,14,"['MS-PowerPoint', 'MS-Excel', 'Effective Commu...",Not actively hiring
7905,Qualcomm,Interim Engineering Intern,Competitive stipend,15,"['Linux', 'Unix', 'C Programming', 'C++ Progra...",Not actively hiring
7906,Qualcomm,Interim Engineering Intern,Competitive stipend,16,"['MATLAB', 'Linux', 'Unix', 'Algorithms', 'C P...",Not actively hiring