In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [2]:
final=pd.DataFrame()
for a in range(1,199):
    url='https://internshala.com/internships/page-{}/'.format(a)
    webpage=requests.get(url).text
    soup=BeautifulSoup(webpage,'lxml')
    company=soup.find_all('div',class_="internship_meta duration_meta")
    name=[]
    stipend=[]
    location=[]
    hiring=[]
    all_skills = [] 
    for i in company:
        name.append(i.find("p").text.strip())
        stipend.append(i.find("span",class_="stipend").text.removesuffix("/month"))
        location.append(i.find("span").text)
        badge = i.find("div", class_="actively-hiring-badge")
        hiring.append(badge.text if badge else "Not actively hiring")

        company_skills = []
        skill_divs = i.find_all("div", class_="job_skill")
        for div in skill_divs:
            company_skills.append(div.text.strip())
        all_skills.append(company_skills)
    df = pd.DataFrame({
    'Name':name,'location':location,'stipend':stipend,"company_id": range(len(all_skills)),
    "skills": all_skills,"hiring":hiring
    })
    final = pd.concat([final, df], ignore_index=True)

In [3]:
final

,Name,location,stipend,company_id,skills,hiring
0,Unacademy,\nBangalore,"₹ 15,000 - 20,000",0,"[Video Editing, Hindi Proficiency (Spoken)]",Actively hiring
1,Export Genius,"\nDelhi, Rohini","₹ 10,000 - 12,000",1,"[Digital Marketing, Email Marketing, Sales Man...",Actively hiring
2,ConnectingDots Infotech,\nPune,"₹ 15,000 - 25,000",2,"[Email Marketing, LinkedIn Marketing, English ...",Actively hiring
3,UpGrad,\nDera Bassi,"₹ 11,000",3,[Effective Communication],Actively hiring
4,Visomni Technologies,\nRaipur,"₹ 10,000 - 17,500",4,"[OpenCV, Python, Yolo]",Actively hiring
...,...,...,...,...,...,...
7614,Connect Karo,\nRemote,"₹ 5,000 - 10,000",4,"[Social Media Marketing, Leadership, Event Man...",Not actively hiring
7615,Mckinsey,\nBangalore,Competitive stipend,5,"[MS-PowerPoint, MS-Excel, Effective Communicat...",Not actively hiring
7616,Mckinsey,\nBangalore,Competitive stipend,6,"[MS-PowerPoint, MS-Excel, Effective Communicat...",Not actively hiring
7617,Qualcomm,\nBangalore,Competitive stipend,7,"[Linux, Unix, C Programming, C++ Programming, ...",Not actively hiring
7618,Qualcomm,\nHyderabad,Competitive stipend,8,"[MATLAB, Linux, Unix, Algorithms, C Programmin...",Not actively hiring

In [5]:
file_path ="WebScraping_Data.csv"

In [6]:
final.to_csv(file_path, index=False, encoding="utf-8")

In [11]:
df=pd.read_csv("WebScraping_Data.csv")

In [12]:
df

,Name,location,stipend,company_id,skills,hiring
0,Unacademy,\nBangalore,"₹ 15,000 - 20,000",0,"['Video Editing', 'Hindi Proficiency (Spoken)']",Actively hiring
1,Export Genius,"\nDelhi, Rohini","₹ 10,000 - 12,000",1,"['Digital Marketing', 'Email Marketing', 'Sale...",Actively hiring
2,ConnectingDots Infotech,\nPune,"₹ 15,000 - 25,000",2,"['Email Marketing', 'LinkedIn Marketing', 'Eng...",Actively hiring
3,UpGrad,\nDera Bassi,"₹ 11,000",3,['Effective Communication'],Actively hiring
4,Visomni Technologies,\nRaipur,"₹ 10,000 - 17,500",4,"['OpenCV', 'Python', 'Yolo']",Actively hiring
...,...,...,...,...,...,...
7614,Connect Karo,\nRemote,"₹ 5,000 - 10,000",4,"['Social Media Marketing', 'Leadership', 'Even...",Not actively hiring
7615,Mckinsey,\nBangalore,Competitive stipend,5,"['MS-PowerPoint', 'MS-Excel', 'Effective Commu...",Not actively hiring
7616,Mckinsey,\nBangalore,Competitive stipend,6,"['MS-PowerPoint', 'MS-Excel', 'Effective Commu...",Not actively hiring
7617,Qualcomm,\nBangalore,Competitive stipend,7,"['Linux', 'Unix', 'C Programming', 'C++ Progra...",Not actively hiring
7618,Qualcomm,\nHyderabad,Competitive stipend,8,"['MATLAB', 'Linux', 'Unix', 'Algorithms', 'C P...",Not actively hiring